identifier: lcxcgefc00w35a4c
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: cs-blog
homeFolder: /Users/chrisschedler/Website/cs-blog
distFolder: dist/cs-blog
outDir: /Users/chrisschedler/Website/cs-blog/docs
handle404: ''
allowErrorCollect: true
